/*
 * File: app/store/StatesStore.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PlanezSphere.store.StatesStore', {
    extend: 'Ext.data.Store',

    requires: [
        'PlanezSphere.model.StatesModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'PlanezSphere.model.StatesModel',
            storeId: 'StatesStore',
            proxy: {
                type: 'ajax',
                url: '_data/read_States.php',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});