/*
 * File: app/view/PasswordReset.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PlanezSphere.view.PasswordReset', {
    extend: 'Ext.window.Window',
    alias: 'widget.passwordReset',

    requires: [
        'Ext.container.Container',
        'Ext.form.Label',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    answer: 'i dont know',
    email: 'nobody@dcrpos.com',
    height: 278,
    id: 'passwordReset',
    width: 484,
    bodyPadding: 10,
    title: 'I forgot my Password',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'label',
                            margins: '0 0 10 0',
                            itemId: 'lblWelcomeForgottenUser'
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'txtResetQuestion',
                            fieldLabel: 'Your Question is',
                            labelAlign: 'right',
                            labelWidth: 150,
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'txtResetAnswer',
                            fieldLabel: 'Answer',
                            labelAlign: 'right',
                            labelWidth: 150,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'txtResetEmail',
                            fieldLabel: 'Enter Email Address',
                            labelAlign: 'right',
                            labelWidth: 150,
                            allowBlank: false
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                pack: 'end',
                                padding: 5
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    margins: '0 5 0 5',
                                    itemId: 'btnResetCancel',
                                    width: 100,
                                    text: 'Cancel'
                                },
                                {
                                    xtype: 'button',
                                    margins: '0 5 0 5',
                                    itemId: 'btnResetSubmit',
                                    width: 100,
                                    text: 'Submit'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            margins: '10 0 0 0',
                            id: 'resetHiddenFields',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    itemId: 'txtResetPassword',
                                    fieldLabel: 'Password',
                                    labelAlign: 'right',
                                    labelWidth: 150,
                                    inputType: 'password'
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'txtResetConfirm',
                                    fieldLabel: 'Confirm Password',
                                    labelAlign: 'right',
                                    labelWidth: 150,
                                    inputType: 'password'
                                },
                                {
                                    xtype: 'container',
                                    margins: '10 0 0 0',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            itemId: 'btnResetPasswordFinished',
                                            maxWidth: 100,
                                            width: 100,
                                            text: 'Set Password'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container'
                }
            ]
        });

        me.callParent(arguments);
    },

    insertUsername: function(username, question, answer, email) {
        Ext.ComponentQuery.query('#lblWelcomeForgottenUser')[0].setText('Welcome ' + username);
        Ext.ComponentQuery.query('#txtResetQuestion')[0].setValue(question);
        email = email.replace('}','');
        this.answer = answer;
        this.email = email;

    }

});