/*
 * File: app/view/SecurityQuestion.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PlanezSphere.view.SecurityQuestion', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.container.Container',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    height: 152,
    id: 'securityQuestion',
    width: 545,
    title: 'Assign a Security Question',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    padding: 10,
                    items: [
                        {
                            xtype: 'combobox',
                            itemId: 'comboSecurity',
                            width: 500,
                            fieldLabel: 'Select Security Question',
                            labelAlign: 'right',
                            labelWidth: 200,
                            displayField: 'question',
                            store: 'SecurityQuestionStore',
                            valueField: 'id'
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'txtSecurity',
                            fieldLabel: 'Answer',
                            labelAlign: 'right',
                            labelWidth: 200
                        },
                        {
                            xtype: 'container',
                            margin: 10,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                pack: 'end',
                                padding: 5
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'btnCancelSecurity',
                                    margin: '0 5 0 5',
                                    width: 100,
                                    text: 'Cancel'
                                },
                                {
                                    xtype: 'button',
                                    margins: '0 5 0 5 ',
                                    itemId: 'btnSubmitSecurity',
                                    width: 100,
                                    text: 'Submit'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});