/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PlanezSphere.controller.LoginController', {
    extend: 'Ext.app.Controller',

    onLoginButtonClicked: function(button, e, eOpts) {
        var username = Ext.ComponentQuery.query("#txtusername")[0].value;
        var password = Ext.ComponentQuery.query("#txtpassword")[0].value;
        console.log('username=' + username + ",password=" + password);
        if ( username == undefined || username.length == 0){
            Ext.Msg.alert('Error','Please enter a username');
            return;
        }
        if ( password == undefined || password.length == 0){
            Ext.Msg.alert('Error','Please enter a Password');
            return;
        }
        Ext.Ajax.request({
            method:'POST',
            url:'_data/read_Login.php',
            params:{
                'username':username,
                'password':password
            },
            success:function(response){
                try{
                    console.dir(response);
                    var result = response.responseText;
                    var responseArray = response.responseText.split(",");
                    var message = responseArray[1];
                    console.dir(message);
                    var codeArray = message.split(":");
                    console.dir(codeArray);
                    var code = codeArray[1].replace('"','');
                    code = code.replace('}','');
                    console.dir(code);
                    switch(code)
                    {
                        case "0":
                            //document.location='_includes/debug.php';
                            break;
                        case "1":
                            Ext.Msg.alert('Alert','Internal Error 501, NO Username Found');
                            break;
                        case "2":
                            Ext.Msg.alert('Alert','Internal Error 502, No Password found');
                            break;
                        case "3":
                            Ext.Msg.alert('Alert','Internal Error 503, User not found');
                            break;
                        case "4":
                            Ext.Msg.alert('Alert','Internal Error 504, Bad Username');
                            break;
                        case "5":
                            Ext.Msg.alert('Alert','Internal Error 505, Bad Password');
                            break;
                        case "10":
                            //forgot password=1 but security code is fine
                            Ext.Msg.alert('Alert','Internal Error 505, Bad Password');
                            break;
                        case "01":
                            //security question needs set but forgot is ok
                            Ext.Msg.alert('Alert','Internal Error 505, Bad Password');
                            break;
                        case "11":
                            //security question needs set and forgot password needs set
                            Ext.Msg.alert('Alert','Internal Error 505, Bad Password');
                            break;
                        default:
                            Ext.Msg.alert('Alert','Internal Error 506, Internal Default Error');
                            break;
                    }
                } catch (e){
                    Ext.Msg.alert('Error','The Server returned an unknown error:507');
                }

            }
        });
    },

    onLoginfieldSpecialkey: function(field, e, eOpts) {
        if ( e.getKey() == e.ENTER){
            //lets try to log in
            var loginbutton = Ext.ComponentQuery.query('#btnlogin')[0];
            loginbutton.fireEvent('click',loginbutton);
        }
    },

    onCancelChangePassword_clicked: function(button, e, eOpts) {
        var cp = Ext.getCmp('wdwChangePassword');
        cp.close();
    },

    onSubmitChangePassword_clicked: function(button, e, eOpts) {

    },

    onChangePasswordSpecialKeyUp: function(field, e, eOpts) {

    },

    init: function(application) {
        this.control({
            "#btnlogin": {
                click: this.onLoginButtonClicked
            },
            "#txtpassword": {
                specialkey: this.onLoginfieldSpecialkey
            },
            "#btnCancelChangePassword": {
                click: this.onCancelChangePassword_clicked
            },
            "#btnSubmitChangePassword": {
                click: this.onSubmitChangePassword_clicked
            },
            "#txtConfirmPassword": {
                specialkey: this.onChangePasswordSpecialKeyUp
            }
        });
    }

});
