/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PlanezSphere.controller.LoginController', {
    extend: 'Ext.app.Controller',

    models: [
        'SecurityQuestionModel'
    ],
    stores: [
        'SecurityQuestionStore'
    ],
    views: [
        'ForgotPassword',
        'SecurityQuestion',
        'PasswordReset'
    ],

    onLoginButton_Click: function(button, e, eOpts) {
        var username = Ext.ComponentQuery.query("#txtusername")[0].value;
        var password = Ext.ComponentQuery.query("#txtpassword")[0].value;

        if ( username === undefined || username.length === 0){
            Ext.Msg.alert('Error','Please enter a username');
            return;
        }
        if ( password === undefined || password.length === 0){
            Ext.Msg.alert('Error','Please enter a Password');
            return;
        }
        Ext.Ajax.request({
            method:'POST',
            url:'_data/read_Login.php',
            params:{
                'username':username,
                'password':password
            },
            success:function(response){
                try{
                    var decode = Ext.decode(response.responseText);
                    console.dir(decode);
                    var result = response.responseText;
                    var responseArray = response.responseText.split(",");
                    var message = responseArray[1];
                    var codeArray = message.split(":");
                    var code = codeArray[1].replace('"','');
                    code = code.replace('}','');
                    switch(code)
                    {
                        case "0":
                            doLogin();
                            break;
                        case "1":
                            Ext.Msg.alert('Alert','Internal Error 501, No Username Found');
                            break;
                        case "2":
                            Ext.Msg.alert('Alert','Internal Error 502, No Password found');
                            break;
                        case "3":
                            Ext.Msg.alert('Alert','Internal Error 503, User not found');
                            break;
                        case "4":
                            Ext.Msg.alert('Alert','Internal Error 504, Bad Username');
                            break;
                        case "5":
                            Ext.Msg.alert('Alert','Internal Error 505, Bad Password');
                            break;
                        case "10":
                            //forgot password=1 but security code is fine
                            var fp = Ext.create('PlanezSphere.view.ForgotPassword',{

                            });
                            fp.show();
                            doLogin();
                            break;
                        case "01":
                            //security question needs set but forgot is ok
                            var sq = Ext.create('PlanezSphere.view.SecurityQuestion',{});
                            sq.show();
                            doLogin();
                            break;
                        case "11":
                            //security question needs set and forgot password needs set
                            var fp1 = Ext.create('PlanezSphere.view.ForgotPassword',{

                            });
                            fp1.on('close',function(e){
                                var sq = Ext.create('PlanezSphere.view.SecurityQuestion',{});
                                sq.show();
                                doLogin();
                            });
                            fp1.show();

                            break;
                        default:
                            Ext.Msg.alert('Alert','Internal Error 509, Internal Default Error');
                            break;
                    }
                } catch (e){
                    Ext.Msg.alert('Error','The Server returned an unknown error:510');
                }

            }
        });

        function doLogin(){
            var cardLayout = Ext.getCmp('masterCardLayout');
            cardLayout.getLayout().setActiveItem(1);
        }
    },

    onLoginfieldSpecialkey: function(field, e, eOpts) {
        if ( e.getKey() == e.ENTER){
            //lets try to log in
            var loginbutton = Ext.ComponentQuery.query('#btnlogin')[0];
            loginbutton.fireEvent('click',loginbutton);
        }
    },

    onCancelChangePassword_click: function(button, e, eOpts) {
        var cp = Ext.getCmp('wdwChangePassword');
        cp.close();
    },

    onSubmitChangePassword_click: function(button, e, eOpts) {
        var p1 = Ext.ComponentQuery.query('#changePassword')[0].value;
        var p2 = Ext.ComponentQuery.query('#confirmPassword')[0].value;


        if ( p1 !== p2){
            Ext.Msg.alert('Error','Your Passwords do not match');
            return;
        }

        Ext.Ajax.request({
            method:'POST',
            url:'_data/update_Login.php',
            params:{
                'password':p1
            },
            success:function(response){
                var parser = Ext.create('PlanezSphere.parse.c5Parse',{

                });
                if ( parser.parseAjax(response) == true){
                    var pw = Ext.getCmp('forgotPassword');
                    pw.close();
                }
            }
        });

    },

    onChangePasswordSpecialKeyUp: function(field, e, eOpts) {
        var button = Ext.ComponentQuery.query('#btnSubmitChangePassword')[0];
        button.fireEvent('click',button);
    },

    onCancelSecurity_click: function(button, e, eOpts) {
        var sqw = Ext.getCmp('securityQuestion');
        sqw.close();
    },

    onSubmitSecurity_click: function(button, e, eOpts) {
        var question = Ext.ComponentQuery.query('#comboSecurity')[0].value;


        var answer = Ext.ComponentQuery.query('#txtSecurity')[0].value;


        if ( question === undefined ){
            Ext.Msg.alert('Error','Please select a question first');
            return;
        }

        if ( answer === undefined || answer.length === 0){
            Ext.Msg.alert('Error','Please answer the question');
            return;
        }

        //now that all is well, we can send the answer and question off to the server
        Ext.Ajax.request({
            method:'POST',
            url:'_data/update_Security.php',
            params:{
                'question':question,
                'answer':answer
            },
            success:function(response){
                var parser = Ext.create('PlanezSphere.parse.c5Parse',{});
                if (parser.parseAjax(response) === true){
                    var sqw = Ext.getCmp('securityQuestion');
                    sqw.close();
                }
            }
        });
    },

    onForgotPassword_click: function(button, e, eOpts) {
        var cid = 'PlanezSphere.view.PasswordReset';
        var shortname = cid.substr(cid.lastIndexOf(".")+1,cid.length);
        if(Ext.get(shortname) != null){
            Ext.get(shortname).destroy();
        }

        var fp = Ext.create('PlanezSphere.view.PasswordReset',{
            height:196
        });
        Ext.getCmp('resetHiddenFields').setVisible(false);


        var username = Ext.ComponentQuery.query('#txtusername')[0].value;
        if ( username === undefined || username.length === 0){
            Ext.Msg.alert('Error','Please enter your username before pressing the forgot password button');
            return;
        }



        //get the security question from the users account to display
        Ext.Ajax.request({
            method:'POST',
            url:'_data/read_UsersSecurity.php',
            params:{
                'username':username
            },
            success:function(response){

                var parser = Ext.create('PlanezSphere.parse.c5Parse',{

                });
                if ( parser.parseAjax(response) === true){

                    //now we need to parse out the question and answer out of the json string
                    var args = response.responseText.split(',');
                    //console.dir(args);

                    var question = args[6].split(':');
                    var answer = args[5].split(':');
                    var email = args[7].split(':');


                    question = question[1];
                    question = question.replace(/\"/g,"");

                    answer = answer[1];
                    answer = answer.replace(/\"/g,"");

                    email = email[1];
                    email = email.replace(/\"/g,"");

                    //console.log('q=' + question + ",a=" + answer + ",e=" + email);

                    fp.insertUsername(username,question,answer,email);
                    fp.show();
                } else {
                    console.log('false');
                }
            }
        });

    },

    onResetCancel_click: function(button, e, eOpts) {
        var rc = Ext.getCmp('passwordReset');
        rc.close();
    },

    onResetSubmit_click: function(button, e, eOpts) {
        var answer = Ext.ComponentQuery.query('#txtResetAnswer')[0].value;
        if ( answer === undefined || answer.length === 0){
            Ext.Msg.alert('Error','Please answer the Security Question');
            return;
        }

        var email = Ext.ComponentQuery.query('#txtResetEmail')[0].value;
        if ( email === undefined || email.length === 0 ){
            Ext.Msg.alert('Error','Please enter an Email address');
            return;
        }

        var localanswer = Ext.getCmp('passwordReset').answer;
        console.log(localanswer);
        if ( localanswer != answer){
            Ext.Msg.alert('Error','Your answer is incorrect');
            Ext.ComponentQuery.query('#txtResetAnswer')[0].focus(false,200);
            return;
        }

        var localemail = Ext.getCmp('passwordReset').email;

        if ( localemail !== email){
            Ext.Msg.alert('Error','Email does not match Account');
            Ext.ComponentQuery.query('#txtResetEmail')[0].focus(false,200);
            return;
        }


        //now show the new password fields
        var pr = Ext.getCmp('passwordReset');
        pr.height = 320;
        Ext.getCmp('resetHiddenFields').setVisible(true);

        console.log('success');



    },

    onFinishResettingPassword_click: function(button, e, eOpts) {
        console.log('we should not be here right now!!!!!');
        var p1 = Ext.ComponentQuery.query('#txtResetPassword')[0].value;
        var p2 = Ext.ComponentQuery.query('#txtResetConfirm')[0].value;
        if ( p1 === undefined || p1.length === 0){
            Ext.Msg.alert('Error', 'Please enter a password');
            return;
        }

        if ( p2 === undefined || p2.length === 0){
            Ext.Msg.alert('Error','Please confirm password');
            return;
        }

        if ( p1 !== p2 ){
            Ext.Msg.alert('Error','Your passwords do not match');
            return;
        }

        var username = Ext.ComponentQuery.query('#lblWelcomeForgottenUser')[0].text;
        var pos = username.indexOf(' ');
        username = username.substring(pos,username.length);


        Ext.Ajax.request({
            method:'POST',
            url:'_data/update_ResetPassword.php',
            params:{
                'username':username,
                'password':p1
            },
            success:function(response){
                var parser = Ext.create('PlanezSphere.parse.c5Parse',{});
                if ( parser.parseAjax(response) === true){
                    Ext.getCmp('passwordReset').close();
                }
            }
        });

    },

    onResetPasswordFinishedButton_click: function(button, e, eOpts) {
        var p1 = Ext.ComponentQuery.query('#txtResetPassword')[0].value;
        var p2 = Ext.ComponentQuery.query('#txtResetConfirm')[0].value;
        if ( p1 === undefined || p1.length === 0){
            Ext.Msg.alert('Error', 'Please enter a password');
            return;
        }

        if ( p2 === undefined || p2.length === 0){
            Ext.Msg.alert('Error','Please confirm password');
            return;
        }

        if ( p1 !== p2 ){
            Ext.Msg.alert('Error','Your passwords do not match');
            return;
        }

        var username = Ext.ComponentQuery.query('#lblWelcomeForgottenUser')[0].text;
        var pos = username.indexOf(' ');
        username = username.substring(pos,username.length);


        Ext.Ajax.request({
            method:'POST',
            url:'_data/update_ResetPassword.php',
            params:{
                'username':username,
                'password':p1
            },
            success:function(response){
                var parser = Ext.create('PlanezSphere.parse.c5Parse',{});
                if ( parser.parseAjax(response) === true){
                    Ext.getCmp('passwordReset').close();
                }
            }
        });

    },

    init: function(application) {
        this.control({
            "#btnlogin": {
                click: this.onLoginButton_Click
            },
            "#txtpassword": {
                specialkey: this.onLoginfieldSpecialkey
            },
            "#btnCancelChangePassword": {
                click: this.onCancelChangePassword_click
            },
            "#btnSubmitChangePassword": {
                click: this.onSubmitChangePassword_click
            },
            "#confirmPassword": {
                specialkey: this.onChangePasswordSpecialKeyUp
            },
            "#btnCancelSecurity": {
                click: this.onCancelSecurity_click
            },
            "#btnSubmitSecurity": {
                click: this.onSubmitSecurity_click
            },
            "#btnForgotPassword": {
                click: this.onForgotPassword_click
            },
            "#btnResetCancel": {
                click: this.onResetCancel_click
            },
            "#btnResetSubmit": {
                click: this.onResetSubmit_click
            },
            "#btnResetFinishPassword": {
                click: this.onFinishResettingPassword_click
            },
            "#btnResetPasswordFinished": {
                click: this.onResetPasswordFinishedButton_click
            }
        });
    }

});
